COURSE_ACTS(COURSE_BOB, _(" 1 BATTAGLIA DI BOB-OMBE"),
       _("BOSS BOB-OMBA SULLA CIMA")     , _("GARA CON KOOPA IL VELOCE") , _("SPARA ALL'ISOLA VOLANTE"),
       _("TROVA LE 8 MONETE ROSSE")      , _("MARIO SPICCA IL VOLO")     , _("OLTRE IL CANCELLO DI CATEGNACCIO"))

COURSE_ACTS(COURSE_WF, _(" 2 FORTEZZA DI WOMP"),
       _("SCHIACCIA WOMP")                 , _("IN CIMA ALLA FORTEZZA")           , _("LANCIO NEL BLU DIPINTO DI BLU"),
       _("MONETE ROSSE SULL'ISOLA SOSPESA"), _("CADUTA SULL'ISOLA INGABBIATA")    , _("DISTRUGGI IL MURO"))

COURSE_ACTS(COURSE_JRB, _(" 3 BAIA PIRATA"),
       _("IL BOTTINO DELLA NAVE AFFONDATA")    , _("VOGLIO GIOCARE CON L'ANGUILLA!") , _("TESORO NELLA GROTTA SUBACQUEA"),
       _("MONETE ROSSE SULLA NAVE")            , _("AFFERRA IL PILASTRO IN PIETRA")  , _("CONTRO CORRENTE"))

COURSE_ACTS(COURSE_CCM, _(" 4 MONTE REFRIGERIO"),
       _("SCIVOLANDO VERSO LA META")             , _("LA PINGUINA SMARRITA...")          , _("SFIDA AL PINGUINO GIGANTE"),
       _("LE 8 MONETE ROSSE DA SCIVOLO")         , _("IL PUPAZZO HA PERSO LA TESTA")     , _("IL SUPER SALTO A PARETE DI MARIO"))

COURSE_ACTS(COURSE_BBH, _(" 5 RIFUGIO DI RE BOO"),
       _("A CACCIA DI FANTASMI")            , _("LA GIOSTRA DEL RE BOO")    , _("I SEGRETI DEI LIBRI POSSEDUTI"),
       _("CERCA LE 8 MONETE ROSSE")         , _("IL BALCONE DI RE BOO")     , _("OCCHI APERTI NELLA STANZA SEGRETA!"))

COURSE_ACTS(COURSE_HMC, _(" 6 GROTTA LABIRINTO"),
       _("MOSTRO ACQUATICO NELLA GROTTA")  , _("SALI PER LE 8 MONETE")                 , _("MARIO, CHE UOMO DI FERRO!"),
       _("NEL LABIRINTO VELENOSO")         , _("ANCHE I LABIRINTI HANNO UN'USCITA")    , _("ROTOLAMENTO MASSI"))

COURSE_ACTS(COURSE_LLL, _(" 7 LAGO DI LAVA"),
       _("FALLO CUOCERE NEL SUO BRODO!")       , _("PRENDILI PER LE CORNA")     , _("PUZZLE A 15 PEZZI PER 8 MONETE"),
       _("CORSA SUL TRONCO ARDENTE")           , _("SUL PENDIO DEL VULCANO")    , _("DENTRO IL VULCANO"))

COURSE_ACTS(COURSE_SSL, _(" 8 DESERTO INGOIATUTTO"),
       _("TRA GLI ARTIGLI DEL GRANDE UCCELLO") , _("LA PUNTA DELLA PIRAMIDE")      , _("ALL'ESPLORAZIONE DELLA PIRAMIDE"),
       _("I QUATTRO PILASTRI")                 , _("LE 8 MONETE IN VOLO LIBERO")   , _("PUZZLE PIRAMIDALE"))

COURSE_ACTS(COURSE_DDD, _(" 9 ABISSO ACQUATICO"),
       _("IL SOTTOMARINO DI BOWSER")      , _("SCRIGNI PORTATI DALLA CORRENTE")    , _("SALTANDO DI PALO IN... MONETA ROSSA"),
       _("CONTRO CORRENTE")               , _("LA RICOMPENSA DELLA MANTA")         , _("NELLA GABBIA"))

COURSE_ACTS(COURSE_SL, _("10 TERRA INNEVATA"),
       _("IL PUPAZZO SI E' MONTATO LA TESTA")     , _("RAFFREDDA I BOLLENTI SPIRITI")       , _("NEL CUBO GHIACCIATO"),
       _("VOLA OLTRE IL LAGO GELATO")             , _("LE 8 MONETE GHIACCIATE")             , _("DENTRO L'IGLOO"))

COURSE_ACTS(COURSE_WDW, _("11 BAGNA ASCIUGA"),
       _("SALE O SCENDE?")                      , _("SOPRA LA CITTA'")             , _("I 5 SEGRETI DALL'ALTO IN BASSO"),
       _("ASCENSORE ESPRESSO - AFFRETTARSI!")   , _("MONETE ROSSE IN CITTA'")      , _("GARA IN CENTRO!"))

COURSE_ACTS(COURSE_TTM, _("12 MONTE GIGANTE"),
       _("UNA MONTAGNA DA SCALARE")         , _("IL SEGRETO DELLA GABBIA")         , _("MONETE ROSSE E FUNGHI SPAVENTOSI"),
       _("PENDIO MONTANO MISTERIOSO")       , _("PANORAMA MOZZAFIATO DAL PONTE")   , _("IL FUNGO SOLITARIO"))

COURSE_ACTS(COURSE_THI, _("13 ISOLA GRANPICCOLA"),
       _("FAI FUORI I FIORI PIRANHA")    , _("IL CUCUZZOLO DELL'ISOLA")            , _("RIVINCITA CON KOOPA IL VELOCE"),
       _("I 5 GRANPICCOLI SEGRETI")      , _("LE MONETE ROSSE DEL TORCIBRUCO")     , _("FILO DA TORCERE PER TORCIBRUCO"))

COURSE_ACTS(COURSE_TTC, _("14 PENDOLO TICTOCCATO"),
       _("GIRA VERSO LA GABBIA")      , _("IL FOSSATO E I PENDOLI")   , _("DAMMI UNA MANO"),
       _("SALTA SUL TWOMP")           , _("SALTI SINCRONIZZATI")      , _("FERMA IL TEMPO PER LE MONETE ROSSE"))

COURSE_ACTS(COURSE_RR, _("15 CAMMINO ARCOBALENO"),
       _("IN CROCIERA SULL'ARCOBALENO")  , _("LA GRANDE CASA NEL CIELO")    , _("MONETE NEL LABIRINTO"),
       _("DONDOLANDO NELLA BREZZA")      , _("TRIANGOLI TRADITORI!")        , _("SOPRA L'ARCOBALENO"))

SECRET_STAR(COURSE_BITDW, _("   BOWSER AL BUIO"))
SECRET_STAR(COURSE_BITFS, _("   BOWSER NEL LAGO DI LAVA"))
SECRET_STAR(COURSE_BITS, _("   BOWSER IN CIELO"))
SECRET_STAR(COURSE_PSS, _("   LO SCIVOLO DEL CASTELLO"))
SECRET_STAR(COURSE_COTMC, _("   CAVERNA DI METALLO"))
SECRET_STAR(COURSE_TOTWC, _("   TORRE DEL CAPPELLO ALATO"))
SECRET_STAR(COURSE_VCUTM, _("   CAPPELLO DELL'INVISIBILITA' SOTTO IL FOSSATO"))
SECRET_STAR(COURSE_WMOTR, _("   SOPRA L'ARCOBALENO"))
SECRET_STAR(COURSE_SA, _("   L'ACQUARIO SEGRETO"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("   STELLE DEL CASTELLO"))

EXTRA_TEXT(0, _("UNA DELLE STELLE SEGRETE DEL CASTELLO!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
