COURSE_ACTS(COURSE_BOB, _(" 1 BATTAGLIA DI BOB-OMBE"),
       _("BOSS BOB-OMBA SULLA CIMA")     , _("GARA CON KOOPA IL VELOCE") , _("SPARA ALL'ISOLA VOLANTE"),
       _("TROVA LE 8 MONETE ROSSE")      , _("MARIO SPICCA IL VOLO")     , _("OLTRE IL CANCELLO DI CATEGNACCIO"))

COURSE_ACTS(COURSE_WF, _(" 2 FORTEZZA DI WOMP"),
       _("SCHIACCIA WOMP")                 , _("IN CIMA ALLA FORTEZZA")           , _("LANCIO NEL BLU DIPINTO DI BLU"),
       _("MONETE ROSSE SULL'ISOLA SOSPESA"), _("CADUTA SULL'ISOLA INGABBIATA")    , _("DISTRUGGI IL MURO"))

COURSE_ACTS(COURSE_JRB, _(" 3 BAIA PIRATA"),
       _("IL BOTTINO DELLA NAVE AFFONDATA")    , _("VOGLIO GIOCARE CON L'ANGUILLA!") , _("TESORO NELLA GROTTA SUBACQUEA"),
       _("MONETE ROSSE SULLA NAVE")            , _("AFFERRA IL PILASTRO IN PIETRA")  , _("CONTRO CORRENTE"))

COURSE_ACTS(COURSE_CCM, _(" 4 MONTE REFRIGERIO"),
       _("SCIVOLANDO VERSO LA META")             , _("LA PINGUINA SMARRITA...")            , _("SFIDA AL PINGUINO GIGANTE"),
       _("LE 8 MONETE ROSSE DA SCIVOLO")         , _("IL PUPAZZO HA PERSO LA TESTA")       , _("IL SUPER SALTO A PARETE DI MARIO"))

COURSE_ACTS(COURSE_BBH, _(" 5 RIFUGIO DI RE BOO"),
       _("GO ON A GHOST HUNT")            , _("RIDE BIG BOO'S MERRY-GO-ROUND") , _("SECRET OF THE HAUNTED BOOKS"),
       _("SEEK THE 8 RED COINS")          , _("BIG BOO'S BALCONY")             , _("EYE TO EYE IN THE SECRET ROOM"))

COURSE_ACTS(COURSE_HMC, _(" 6 GROTTA LABIRINTO"),
       _("SWIMMING BEAST IN THE CAVERN")  , _("ELEVATE FOR 8 RED COINS")       , _("METAL-HEAD MARIO CAN MOVE!"),
       _("NAVIGATING THE TOXIC MAZE")     , _("A-MAZE-ING EMERGENCY EXIT")     , _("WATCH FOR ROLLING ROCKS"))

COURSE_ACTS(COURSE_LLL, _(" 7 LAGO DI LAVA"),
       _("BOIL THE BIG BULLY")            , _("BULLY THE BULLIES")             , _("8-COIN PUZZLE WITH 15 PIECES"),
       _("RED-HOT LOG ROLLING")           , _("HOT-FOOT-IT INTO THE VOLCANO")  , _("ELEVATOR TOUR IN THE VOLCANO"))

COURSE_ACTS(COURSE_SSL, _(" 8 DESERTO INGOIATUTTO"),
       _("IN THE TALONS OF THE BIG BIRD") , _("SHINING ATOP THE PYRAMID")      , _("INSIDE THE ANCIENT PYRAMID"),
       _("STAND TALL ON THE FOUR PILLARS"), _("FREE FLYING FOR 8 RED COINS")   , _("PYRAMID PUZZLE"))

COURSE_ACTS(COURSE_DDD, _(" 9 ABISSO ACQUATICO"),
       _("BOARD BOWSER'S SUB")            , _("CHESTS IN THE CURRENT")         , _("POLE-JUMPING FOR RED COINS"),
       _("THROUGH THE JET STREAM")        , _("THE MANTA RAY'S REWARD")        , _("COLLECT THE CAPS..."))

COURSE_ACTS(COURSE_SL, _("10 TERRA INNEVATA"),
       _("SNOWMAN'S BIG HEAD")            , _("CHILL WITH THE BULLY")          , _("IN THE DEEP FREEZE"),
       _("WHIRL FROM THE FREEZING POND")  , _("SHELL SHREDDIN' FOR RED COINS") , _("INTO THE IGLOO"))

COURSE_ACTS(COURSE_WDW, _("11 BAGNA ASCIUGA"),
       _("SHOCKING ARROW LIFTS!")         , _("TOP O' THE TOWN")               , _("SECRETS IN THE SHALLOWS & SKY"),
       _("EXPRESS ELEVATOR--HURRY UP!")   , _("GO TO TOWN FOR RED COINS")      , _("QUICK RACE THROUGH DOWNTOWN!"))

COURSE_ACTS(COURSE_TTM, _("12 MONTE GIGANTE"),
       _("SCALE THE MOUNTAIN")            , _("MYSTERY OF THE MONKEY CAGE")    , _("SCARY 'SHROOMS, RED COINS"),
       _("MYSTERIOUS MOUNTAINSIDE")       , _("BREATHTAKING VIEW FROM BRIDGE") , _("BLAST TO THE LONELY MUSHROOM"))

COURSE_ACTS(COURSE_THI, _("13 ISOLA GRANPICCOLA"),
       _("PLUCK THE PIRANHA FLOWER")      , _("THE TIP TOP OF THE HUGE ISLAND"), _("REMATCH WITH KOOPA THE QUICK"),
       _("FIVE ITTY BITTY SECRETS")       , _("WIGGLER'S RED COINS")           , _("MAKE WIGGLER SQUIRM"))

COURSE_ACTS(COURSE_TTC, _("14 PENDOLO TICTOCCATO"),
       _("ROLL INTO THE CAGE")            , _("THE PIT AND THE PENDULUMS")     , _("GET A HAND"),
       _("STOMP ON THE THWOMP")           , _("TIMED JUMPS ON MOVING BARS")    , _("STOP TIME FOR RED COINS"))

COURSE_ACTS(COURSE_RR, _("15 CAMMINO ARCOBALENO"),
       _("CRUISER CROSSING THE RAINBOW")  , _("THE BIG HOUSE IN THE SKY")      , _("COINS AMASSED IN A MAZE"),
       _("SWINGIN' IN THE BREEZE")        , _("TRICKY TRIANGLES!")             , _("SOMEWHERE OVER THE RAINBOW"))

SECRET_STAR(COURSE_BITDW, _("   BOWSER AL BUIO"))
SECRET_STAR(COURSE_BITFS, _("   BOWSER NEL LAGO DI LAVA"))
SECRET_STAR(COURSE_BITS, _("   BOWSER IN CIELO"))
SECRET_STAR(COURSE_PSS, _("   LO SCIVOLO DEL CASTELLO"))
SECRET_STAR(COURSE_COTMC, _("   CAVERNA DI METALLO"))
SECRET_STAR(COURSE_TOTWC, _("   TORRE DEL CAPPELLO ALATO"))
SECRET_STAR(COURSE_VCUTM, _("   CAPPELLO DELL'INVISIBILITA' SOTTO IL FOSSATO"))
SECRET_STAR(COURSE_WMOTR, _("   SOPRA L'ARCOBALENO"))
SECRET_STAR(COURSE_SA, _("   L'ACQUARIO SEGRETO"))
SECRET_STAR(COURSE_CAKE_END, _(""))

CASTLE_SECRET_STARS(_("   STELLE DEL CASTELLO"))

EXTRA_TEXT(0, _("UNA DELLE STELLE SEGRETE DEL CASTELLO!"))
EXTRA_TEXT(1, _(""))
EXTRA_TEXT(2, _(""))
EXTRA_TEXT(3, _(""))
EXTRA_TEXT(4, _(""))
EXTRA_TEXT(5, _(""))
EXTRA_TEXT(6, _(""))
